
name: Build ZTE F50 Kernel with Droidspaces

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/qwer233qq/android_kernel_zte_ums9620_mifi_f50
          kernel-branch: main
          config: f50_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          android-version: 12
          aosp-clang-version: r416183b
          anykernel3: true
          release: true
          access-token: ${{ secrets.GITHUB_TOKEN }}
